apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: goserver
    kind: deployment
  minReplicas: 1 # produção no mínimo 3, se uma cair tem outras
  maxReplicas: 5 # maximo de replicas quando escalar
  targetCPUUtilizationPercentage: 25 # produção 75 a 80, pois depende do tempo q seu pod leva pra subir
