apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None # sabe q não vai trabalhar com IP, mas com DNS. Vai pedir quais são os pods q precisa criar service, por conta disso serviceName do statefulset tem q ser igual do service