apiVersion: v1
kind: Pod # tipo de objeto q estou criando
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
      - name: goserver
        image: "lndaquino/hello-go:latest"