apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver # vem do deployment, seleciona todos os pods do deployment q tem esse selector
  type: LoadBalancer # são 4 para escolher: ClusterIP, NodePort, LoadBalancer, headless
  ports:
  - name: goserver-service
    port: 80 # porta do service - faz kubectl port-forward svc/goserver-service portaDoComputador:port
    targetPort: 8000 # porta do container para qual serão direcionadas as requisições que acessarem a porta do service
    protocol: TCP